Started on datacatalog harvester, making mapping.

diff --git a/.github/workflows/push_latest_datacatalog.yml b/.github/workflows/push_latest_datacatalog.yml
--- a/.github/workflows/push_latest_datacatalog.yml
+++ b/.github/workflows/push_latest_datacatalog.yml
@@ -1,37 +1,56 @@
 # This is a basic workflow to help you get started with Actions
 
-name: CI
+name: RCE Datacatalog ETL 
+
+env:
+  ARTIFACT_PATH: 'artifact-data.json'
+  GRAPH_ID: 'muurschilderingen-latest-graph'
+
 
 # Controls when the workflow will run
 on:
-  # Triggers the workflow on push or pull request events but only for the "main" branch
-  push:
-    branches: [ "main" ]
-  pull_request:
-    branches: [ "main" ]
-
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
-  build:
-    # The type of runner that the job will run on
-    runs-on: ubuntu-latest
-
-    # Steps represent a sequence of tasks that will be executed as part of the job
+  get-latest-datacatalog:
+    runs-on: ubuntu-latest 
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v4
+    - name: get-latest-datacatalog 
+      run: curl --data-urlencode "query=[[Categorie:Datasets]]|limit=500|?Dataset type|?Zichtbaar in Erfgoedatlas|?Dataset domein|?Waar te vinden" --data-urlencode "format=json" https://kennis.cultureelerfgoed.nl/api.php?action=ask >> datasetregister.json  
+    - name: Upload data artifact
+      uses: actions/upload-artifact@v4
+      with:
+        name: data-artifact
+        path: ${{ env.ARTIFACT_PATH }}
+        overwrite: true
+        retention-days: 1
 
-      # Runs a single command using the runners shell
-      - name: Run a one-line script
-        run: echo Hello, world!
+  push-to-triply:
+    runs-on: ubuntu-latest
+    needs: [get-latest-datacatalog]
+    steps:
+    - name: Download data artifact
+      uses: actions/download-artifact@v4
+      with:
+          name: data-artifact
+          path: data
+    - name: Install dependencies
+      run: |
+        wget 'https://static.triply.cc/cli/triplydb-linux'
+        chmod +x triplydb-linux
+        ./triplydb version  # Verificatie stap
+    - name: Push changes to TriplyDB API via CLI
+      run: |
+        ./triplydb-linux import-from-file \ 
+        --dataset "Muurschilderingen" \
+        --token "${{ secrets.LDV_API_TOKEN }}" \ 
+        --account "rce" \
+        --url "https://api.linkeddata.cultureelerfgoed.nl" \ 
+        --default-graph-name "https://linkeddata.cultureelerfgoed.nl/rce/Muurschilderingen/graphs/${{ env.GRAPH_ID }}" \
+        --mode "overwrite" ${{ env.ARTIFACT_PATH }} ||  { 
+            echo "::error::TriplyDB push failed"
+            exit 1
+          }
 
-      # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
-        run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
-      
